"""empty message

Revision ID: 21773a371ec4
Revises: d67ee39dce34
Create Date: 2019-12-14 18:23:41.481261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21773a371ec4'
down_revision = 'd67ee39dce34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'num_upcoming_shows')
    op.add_column('venue', sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'num_upcoming_shows')
    op.add_column('artist', sa.Column('num_upcoming_shows', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
