"""empty message

Revision ID: d67ee39dce34
Revises: ad4139dd9fab
Create Date: 2019-12-14 18:16:56.902577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67ee39dce34'
down_revision = 'ad4139dd9fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'num_upcoming_shows')
    # ### end Alembic commands ###
